[package]
name = "iced"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {git = "https://github.com/iced-rs/iced", rev = "refs/tags/text-editor", features = ["debug", "tokio", "highlighter"]}

tokio = { version = "1.32", features = ["fs"]}

rfd = "0.15.2"

